# Generated by Django 5.0.1 on 2024-03-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('restaurant', models.CharField(choices=[('Harrogate', 'Harrogate'), ('Leeds', 'Leeds'), ('Knaresborough Castle', 'Knaresborough')], max_length=100)),
                ('number_persons', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
